{{- range $key, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $svc.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ $svc.port }}
          envFrom:
            - configMapRef:
                name: {{ $svc.configMap | quote }}
            - secretRef:
                name: {{ $svc.secret | quote }}

          {{- if $svc.resources }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          {{- end }}

          {{- if $svc.healthPath }}
          livenessProbe:
            httpGet:
              path: {{ $svc.healthPath }}
              port: {{ $svc.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: {{ $svc.healthPath }}
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
{{- end }}
