{{- range $svc := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.secret }}
type: Opaque
stringData:
  JWT_SECRET: "changeMeToASecret"
  DB_PASSWORD: "replaceThis"
{{- end }}
